import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Techno - Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let header = (
    <header className="container mx-auto">
      <Link
        href="/"
        className="flex flex-row p-2 justify-center lg:justify-start border-b-1 border-amber-500"
      >
        <h1 className="text-xl font-bold italic text-amber-500">Techno Blog</h1>
      </Link>
    </header>
  );
  let footer = (
    <footer className="text-center py-4">
      <p>
        Made with ❤️ by{" "}
        <a href="https://muntasirsunny.vercel.app/" target="_blank">
          Muntasir Sunny
        </a>
      </p>
    </footer>
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {header}
        <main className="flex-1 w-full container mx-auto px-4">{children}</main>
        {footer}
      </body>
    </html>
  );
}
